mysql:
  # 用户名
  username: root
  # 密码
  password: 20170802
  # 数据库名
  database: music
  # 主机地址
  host: 150.158.145.97
  # 端口
  port: 3306
  # 连接字符串参数
  query: parseTime=True&loc=Local&timeout=10000ms
  # 是否打印日志
  log-mode: true
  # 数据库表前缀(无需再末尾添加下划线, 程序内部自动处理)
  table-prefix: tb
  # 编码方式
  charset: utf8mb4
  # 字符集(utf8mb4_general_ci速度比utf8mb4_unicode_ci快些)
  collation: utf8mb4_general_ci

redis:
  host: 150.158.145.97
  port: 6379
  password: 20170802